version: "3.8"

services:
  spring:
    image: ${DOCKER_USERNAME}/chat-container:latest
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped

  alloy:
    image: grafana/alloy:latest
    depends_on:
      - spring
    environment:
      - LOKI_URL=${LOKI_URL}
      - SERVER_NAME=chat
      - LOKI_ENV=${LOKI_ENV}
      - LOKI_SERVICE_NAME=chat
    volumes:
      - ./logs:/var/log/app
      - ./logging/alloy.yml:/etc/alloy/alloy.yml
    command: run /etc/alloy/alloy.yml
    restart: unless-stopped

networks:
  default:
    name: budong-network
    external: true